### ISSUE TITLE
Error while sending BTC

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/wts.zold.io#102]
I tried to exchange ZLD to BTC, and this is what I saw in the log:

```
ERROR: RuntimeError: Failed to send "3.5232136" to "386M5ERydicUi2uCgbd2vGBVEKspq8d555" with details of "Exchange of 4.00000000 by @emilianodellacasa to 25e0819b40cf7eb6, rate is 0.00025, fee is 0.08": Invalid amount
	/app/objects/bank.rb:56:in `rescue in send'
	/app/objects/bank.rb:51:in `send'
	/app/wts.rb:525:in `block (2 levels) in <top (required)>'
	/app/wts.rb:768:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/clean_job.rb:43:in `call'
	/app/objects/versioned_job.rb:34:in `call'
	/app/objects/zache_job.rb:32:in `call'
	/app/objects/safe_job.rb:34:in `call'
	/app/objects/async_job.rb:41:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:40:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Apparently, the 4ZLD have been deducted from my account

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by yegor256** [comment]
@emilianodellacasa 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#102` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
