### ISSUE TITLE
payment isn't processed because of wrong payment details

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#113]
```
RuntimeError: Wrong details "%40emilianodellacasa%3A+Payment+for+gh%3Azold-io%2Fzold%23356%3A+Order+was+finished%2C+quality+is+%22good%22" ([a-zA-Z0-9 @\!\?\*_\-\.:,'/]+)
  from zold/txn.rb:91:in `initialize'
  from zold/wallet.rb:130:in `new'
  from zold/wallet.rb:130:in `sub'
  from zold/commands/pay.rb:124:in `pay'
  from zold/commands/pay.rb:94:in `block in run'
  from zold/sync_wallets.rb:47:in `block (2 levels) in acq'
  from futex.rb:130:in `block in open'
  from futex.rb:176:in `open_synchronized'
  from futex.rb:103:in `open'
  from zold/sync_wallets.rb:46:in `block in acq'
  from zold/cached_wallets.rb:51:in `block in acq'
  from zold/wallets.rb:71:in `acq'
  from zold/cached_wallets.rb:49:in `acq'
  from zold/sync_wallets.rb:45:in `acq'
  from zold/commands/pay.rb:93:in `run'
  from zold/commands/thread_badge.rb:41:in `run'
  from objects/ops.rb:76:in `block in pay'
  from tempfile.rb:295:in `open'
  from objects/ops.rb:73:in `pay'
  from wts.rb:362:in `block (2 levels) in <top (required)>'
  from wts.rb:775:in `block in job'
  from objects/update_job.rb:47:in `call'
  from objects/clean_job.rb:43:in `call'
  from objects/versioned_job.rb:34:in `call'
  from objects/zache_job.rb:32:in `call'
  from objects/safe_job.rb:35:in `call'
  from objects/async_job.rb:41:in `block (2 levels) in call'
  from futex.rb:130:in `block in open'
  from futex.rb:176:in `open_synchronized'
  from futex.rb:103:in `open'
  from objects/async_job.rb:40:in `block in call'
  from concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  from concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  from concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
  from concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.1`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#113` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
