### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#121]
When I try to login to wts when I'm not authorized at Github I'm getting error page but login successfully.

To reproduce:
 1. start new session (e.g. private window in browser)
 2. go to wts.zold.io click login (browser opens github.com login page)
 3. enter Github username/password, click "Sign in" button
 4. browser opens a page "You are being redirected to authorized application", click "allow redirect" on browser popup. ![scrot-2019-02-16-10 06 24](https://user-images.githubusercontent.com/1524988/52896053-87efa200-31d3-11e9-9823-00812a65d5cb.png)
 4. wts shows error: ![scrot-2019-02-06-13 19 39](https://user-images.githubusercontent.com/1524988/52335119-a1922c00-2a12-11e9-835e-5801adb284ad.png)

stacktrace:
```
RuntimeError: Error (401): {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
	/app/vendor/bundle/ruby/2.6.0/gems/glogin-0.4.7/lib/glogin/auth.rb:62:in `user'
	/app/wts.rb:244:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/handler/thin.rb:22:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
	/app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
	/app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
	/app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
	/app/vendor/bundle/bin/bundle:104:in `load'
	/app/vendor/bundle/bin/bundle:104:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I can't reproduce the problem. Are you sure the description is correct?

**Comment by g4s8** [comment]
@yegor256 yes, it's a stable issue, I've just reproduced it again. To reproduce it, check that you are not logged in github before wts

**Comment by yegor256** [comment]
@g4s8 I honestly can't reproduce. Please, check the description of the steps. Make them more explicit. I don't understand what exactly "get redirect back to wts" means? Make sure the steps are explained like this: "Click this, open window, click that". "Get redirect" is something ambiguous.

**Comment by g4s8** [comment]
@yegor256 updated the ticket

**Comment by yegor256** [comment]
@g4s8 watch this: https://www.youtube.com/watch?v=5A3KFj3xh74 I can't understand where the problem is coming from...

**Comment by yegor256** [comment]
@g4s8 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#121` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
