### ISSUE TITLE
BTC hook is broken

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#135]
```
UserError: You have to login first
2019-02-16T07:57:50.512506+00:00 app[web.1]: /app/wts.rb:872:in `user'
2019-02-16T07:57:50.512508+00:00 app[web.1]: /app/wts.rb:551:in `block (2 levels) in <top (required)>'
2019-02-16T07:57:50.512509+00:00 app[web.1]: /app/wts.rb:931:in `block in job'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#135` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
