### ISSUE TITLE
/job API may return error before OK status

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#143]
I'm trying to send ZLD using pay API and waiting with /job API.
When I'm checking /job response I'm getting `Running` statuses, then error with 303 code, and then 200 `OK` status. API returns error before `OK` and payment was sent successfully. Reproduced twice.

Error:
```
UserError: Job ID 2bae9693-23a6-444a-af19-3cb167af7750 is not found
    /app/wts.rb:713:in `block in <top (required)>'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
    /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
    /app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
    /app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
    /app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/handler/thin.rb:22:in `run'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
    /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
    /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
    /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
    /app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
    /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
    /app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
    /app/vendor/bundle/bin/bundle:104:in `load'
    /app/vendor/bundle/bin/bundle:104:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed in 0962ffb70638cf363c3ed1b401c4571eb2e6e694 Try again please.

**Comment by g4s8** [comment]
@yegor256 now I'm getting new error, does it related to this fix?
```
Futex::CantLock: #4-ex/remotes-32@116.203.73.225:4096[/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:257:in `modify'] can't get exclusive access to the file /app/.zold-wts/remotes because of the lock at /app/.zold-wts/remotes.lock, after 16.0s of waiting: #4-ex/remotes-61@95.216.22.87:4096[/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:257:in `modify'] (modified 20ms ago)
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:116:in `block (2 levels) in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:105:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:105:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:257:in `modify'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:274:in `if_present'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:227:in `error'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:217:in `rescue in block in iterate'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:212:in `block in iterate'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:88:in `block (3 levels) in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:85:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:85:in `block (2 levels) in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:56:in `block (2 levels) in start'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/verbose_thread.rb:41:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:44:in `block in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:43:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:43:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:55:in `block in start'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/thread_pool.rb:49:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/verbose_thread.rb:41:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/thread_pool.rb:47:in `block in add'
```

**Comment by yegor256** [comment]
@g4s8 nope, it's something else. Please, report another ticket.
