### ISSUE TITLE
Payment sometime fails with Futex::CantLock

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#146]
After call pay API and waiting job to complete with /job API I can receive this error:
```
Futex::CantLock: #4-ex/remotes-32@116.203.73.225:4096[/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:257:in `modify'] can't get exclusive access to the file /app/.zold-wts/remotes because of the lock at /app/.zold-wts/remotes.lock, after 16.0s of waiting: #4-ex/remotes-61@95.216.22.87:4096[/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:257:in `modify'] (modified 20ms ago)
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:116:in `block (2 levels) in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:105:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:105:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:257:in `modify'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:274:in `if_present'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:227:in `error'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:217:in `rescue in block in iterate'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/remotes.rb:212:in `block in iterate'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:88:in `block (3 levels) in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:85:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:85:in `block (2 levels) in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:56:in `block (2 levels) in start'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/verbose_thread.rb:41:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:44:in `block in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:43:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/endless.rb:43:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/hands.rb:55:in `block in start'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/thread_pool.rb:49:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/verbose_thread.rb:41:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.23.10/lib/zold/thread_pool.rb:47:in `block in add'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#146` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
