### ISSUE TITLE
Error in my wallet.

### ISSUE THREAD

**Issue by ebercamargo** [zold-io/wts.zold.io#198]
Plss check this:

```
Just created a new wallet 87a77d9144b8034a, going to push it...
ERROR: WTS::UserError: The wallet 87a77d9144b8034a of 5541996768649 is absent, can't PUSH; most probably you just have to RESTART your wallet
	/app/objects/ops.rb:88:in `push'
	/app/wts.rb:1286:in `block (2 levels) in <top (required)>'
	/app/wts.rb:1534:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/versioned_job.rb:39:in `call'
	/app/objects/tracked_job.rb:33:in `call'
	/app/objects/safe_job.rb:36:in `call'
	/app/objects/async_job.rb:41:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:40:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ebercamargo you just have to RESTART, as the message suggests

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#198` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
