### ISSUE TITLE
Lost ZLDs due to a payment error

### ISSUE THREAD

**Issue by carlosmiranda** [zold-io/wts.zold.io#214]
I just tried withdrawing 256 ZLD (max daily amount) to PayPal. I lost the same amount (plus fee) due to an error; the amount was deducted from my wallet but the PayPal transaction failed.

Here is the log (PayPal account is redacted for privacy reasons - will send separately):

```
Zold gem version: 0.29.27/2
WTS version: 0.0.0
Current time is: 2019-04-15T04:47:30Z
Job ID: edd20e1e-33ef-4aa7-9e49-28edc769e024
The list of 20 remotes trimmed down to 20 nodes
There are 38 known remotes with the overall score of 291, after update in 7.21s
20 best remote nodes were selected to stay in the list
Sending $357.81 via PayPal to xxxxxx@gmail.com...
Pulling 43c46fa1d2a5bfb5 from the network...
20 copies of 43c46fa1d2a5bfb5 fetched in 8.13s with the total score of 163 from 20 nodes (5 master nodes)
Nothing changed in 43c46fa1d2a5bfb5 after merge of 3 copies
Wallet 43c46fa1d2a5bfb5 pulled successfully in 8.48s
Pulling 7a2c2c57a935b3ad from the network...
19 copies of 7a2c2c57a935b3ad fetched in 27.01s with the total score of 158 from 20 nodes (4 master nodes)
Nothing changed in 7a2c2c57a935b3ad after merge of 4 copies
Wallet 7a2c2c57a935b3ad pulled successfully in 33.66s
Pulling 860261987eb8d2d3 from the network...
18 copies of 860261987eb8d2d3 fetched in 36.19s with the total score of 153 from 20 nodes (3 master nodes)
Nothing changed in 860261987eb8d2d3 after merge of 5 copies
Wallet 860261987eb8d2d3 pulled successfully in 41.69s
Paying 250.88ZLD from 43c46fa1d2a5bfb5 to 860261987eb8d2d3...
RTAFtDSI@860261987eb8d2d3
3
The tax debt of 43c46fa1d2a5bfb5/90.1360/36t/2a6399/6Kb is 0.01ZLD (still acceptable)
250.88ZLD arrived to 860261987eb8d2d3: ZLD exchange to 357.81 PayPal, rate is 0.0002704, fee is 0.02
Paid 250.88ZLD from 43c46fa1d2a5bfb5 to 860261987eb8d2d3 in 298ms "ZLD exchange to 357.81 PayPal, rate is 0.0002704, fee is 0.02": #3 2019-04-15T04:49:01Z -250.88ZLD 860261987eb8d2d3 ZLD exchange to 357.81 PayPal, rate is 0.0002704, fee is 0.02
Paying 5.12ZLD from 43c46fa1d2a5bfb5 to 7a2c2c57a935b3ad...
uz6ywCN4@7a2c2c57a935b3ad
4
The tax debt of 43c46fa1d2a5bfb5/85.0160/37t/affc90/7Kb is 0.01ZLD (still acceptable)
5.12ZLD arrived to 7a2c2c57a935b3ad: Fee for exchange of 357.81 PayPal, rate is 0.0002704, fee is 0.02
Paid 5.12ZLD from 43c46fa1d2a5bfb5 to 7a2c2c57a935b3ad in 565ms "Fee for exchange of 357.81 PayPal, rate is 0.0002704, fee is 0.02": #4 2019-04-15T04:49:02Z -5.12ZLD 7a2c2c57a935b3ad Fee for exchange of 357.81 PayPal, rate is 0.0002704, fee is 0.02
Pushing 43c46fa1d2a5bfb5 to the network...
Push finished to 19 nodes (5 master nodes) out of 20 in 22.67s, total score for 43c46fa1d2a5bfb5 is 139
Wallet 43c46fa1d2a5bfb5 pushed successfully in 22.69s
ERROR: NoMethodError: undefined method `xxxxxx@gmail.com' for #<SyncEm:0x00007f215c175ff0>
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.1/lib/syncem.rb:47:in `block in method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.1/lib/syncem.rb:41:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.1/lib/syncem.rb:41:in `method_missing'
	/app/front/front_paypal.rb:122:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:42:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/versioned_job.rb:39:in `call'
	/app/objects/tracked_job.rb:33:in `call'
	/app/objects/safe_job.rb:36:in `call'
	/app/objects/exclusive_job.rb:35:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/exclusive_job.rb:34:in `call'
	/app/objects/async_job.rb:41:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:40:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Comment by 0crat** [comment]
The job [#214](https://github.com/zold-io/wts.zold.io/issues/214) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/f6769385-7e13-4109-b151-cd225add4757); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@yegor256 this is now fixed, I was able to withdraw successfully twice today. THanks

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#214](https://github.com/zold-io/wts.zold.io/issues/214) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
