### ISSUE TITLE
Haml::Error: Invalid US-ASCII character "\xE2"

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#235]
Sometimes this happens:

```
Haml::Error: Invalid US-ASCII character &quot;\xE2&quot;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/engine.rb:57:in `block in initialize&#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/util.rb:81:in `rescue in block in check_encoding&#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/util.rb:78:in `block in check_encoding&#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/util.rb:77:in `each&amp;#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/util.rb:77:in `each_with_index&amp;#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/util.rb:77:in `check_encoding&#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/util.rb:117:in `check_haml_encoding&#39;
        /home/r/.ruby/gems/haml-5.0.4/lib/haml/engine.rb:56:in `initialize&#39;
        /home/r/repo/front/front_quick.rb:30:in `new&#39;
        /home/r/repo/front/front_quick.rb:30:in `block in &lt;top (required)&gt;&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!&amp;#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call&#39;
        /home/r/.ruby/gems/rack_csrf-2.6.0/lib/rack/csrf.rb:38:in `call&#39;
        /home/r/.ruby/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context&#39;
        /home/r/.ruby/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call&#39;
        /home/r/.ruby/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call&#39;
        /home/r/.ruby/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call&#39;
        /home/r/.ruby/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call&#39;
        /home/r/.ruby/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call&#39;
        /home/r/.ruby/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call&#39;
        /home/r/.ruby/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call&#39;
        /home/r/.ruby/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call&#39;
        /home/r/.ruby/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:224:in `call&#39;
        /home/r/.ruby/gems/rack-2.0.6/lib/rack/head.rb:12:in `call&#39;
        /home/r/.ruby/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call&amp;#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize&#39;
        /home/r/.ruby/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call&#39;
        /home/r/.ruby/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request&#39;
        /home/r/.ruby/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request&#39;
        /home/r/.ruby/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request&#39;
        /home/r/.ruby/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/forwardable.rb:230:in `get&#39;
        /home/r/repo/test/test_wts.rb:75:in `block in test_renders_pages&#39;
        /home/r/repo/test/test_wts.rb:74:in `each&#39;
        /home/r/repo/test/test_wts.rb:74:in `test_renders_pages&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `each&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:136:in `run&#39;
        /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun&#39;
```

**Comment by yegor256** [comment]
fixed

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#235` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
