### ISSUE TITLE
can't pull all wallets

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#237]
```
Concurrent::RejectedExecutionError: Concurrent::RejectedExecutionError
  from concurrent/executor/abstract_executor_service.rb:76:in `handle_fallback'
  from concurrent/executor/ruby_thread_pool_executor.rb:152:in `ns_execute'
  from concurrent/executor/ruby_executor_service.rb:22:in `block in post'
  from concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
  from concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
  from concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
  from concurrent/executor/ruby_executor_service.rb:19:in `post'
  from objects/async_job.rb:39:in `call'
  from front/front_jobs.rb:55:in `job'
  from front/front_auto_pull.rb:26:in `block (2 levels) in <top (required)>'
  from front/front_auto_pull.rb:23:in `each'
  from front/front_auto_pull.rb:23:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.9`

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#237` is not assigned, can't get performer
