### ISSUE TITLE
NoMethodError: undefined method `abs' for main:Object

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#246]
```
NoMethodError: undefined method `abs' for main:Object
  from front/front_btc.rb:175:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.3`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#246` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
