### ISSUE TITLE
NoMethodError: private method `sibit' called for Sinatra::Application:Class

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#258]
```
NoMethodError: private method `sibit' called for Sinatra::Application:Class
  from front/front_rate.rb:66:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.20`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.20`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#258` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
