### ISSUE TITLE
Coinbase::Wallet::ValidationError

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#260]
```
Coinbase::Wallet::ValidationError: You currently only have 0.04466300 BTC available ($402.19).
  from coinbase/wallet/api_errors.rb:45:in `check_response_status'
  from coinbase/wallet/adapters/net_http.rb:36:in `http_verb'
  from coinbase/wallet/api_client.rb:687:in `post'
  from coinbase/wallet/api_client.rb:274:in `send'
  from coinbase/wallet/models/account.rb:67:in `send'
  from objects/coinbase.rb:69:in `pay'
  from syncem.rb:43:in `block in method_missing'
  from syncem.rb:41:in `synchronize'
  from syncem.rb:41:in `method_missing'
  from front/front_btc.rb:143:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.22`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#260` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
