### ISSUE TITLE
ArgumentError: flag after precision

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#261]
```
ArgumentError: flag after precision
  from SVG/Graph/Graph.rb:671:in `%'
  from SVG/Graph/Graph.rb:671:in `make_datapoint_text'
  from SVG/Graph/Line.rb:260:in `block (2 levels) in draw_data'
  from SVG/Graph/Line.rb:247:in `each_index'
  from SVG/Graph/Line.rb:247:in `block in draw_data'
  from SVG/Graph/Line.rb:201:in `each'
  from SVG/Graph/Line.rb:201:in `draw_data'
  from SVG/Graph/Graph.rb:213:in `burn'
  from objects/graph.rb:79:in `svg'
  from front/front_rate.rb:157:in `block (2 levels) in <top (required)>'
```

**Comment by yegor256** [comment]
reported: https://github.com/clbustos/svg-graph/issues/13

**Comment by 0crat** [comment]
Job [#261](https://github.com/zold-io/wts.zold.io/issues/261) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
