### ISSUE TITLE
NameError: undefined local variable or method `r' for main:Object

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#265]
```
NameError: undefined local variable or method `r' for main:Object
Did you mean?  rm
  from front/front_rate.rb:190:in `block in hoc'
  from front/front_rate.rb:189:in `map'
  from front/front_rate.rb:189:in `hoc'
  from front/front_rate.rb:79:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.28`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#265` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
