### ISSUE TITLE
There are only edge nodes

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#271]
Zerocracy payment failed with error:
> We are very sorry, but we failed to pay you $10.67 for gh:stryvers/life-lens-app#354: "Failed to pay: Failed to pay via WTS: job=af0c098e-411a-471b-b2dd-7932c3534031 error=WTS::UserError: There are only edge nodes, run 'zold remote update' or use --tolerate-edges

I'm not sure how critical this error, it seems that it was reproduced just few times, and now it's working fine.

Full error:
```
We are very sorry, but we failed to pay you $10.67 for gh:stryvers/life-lens-app#354: "Failed to pay: Failed to pay via WTS: job=af0c098e-411a-471b-b2dd-7932c3534031 error=WTS::UserError: There are only edge nodes, run 'zold remote update' or use --tolerate-edges
 /app/objects/ops.rb:75:in rescue in pull'
 /app/objects/ops.rb:61:in pull'
 /app/front/frontpay.rb:79:in `block (2 levels) in <top (required)>'
 /app/front/frontjobs.rb:43:in block in job'
 /app/objects/update_job.rb:47:in call'
 /app/objects/versionedjob.rb:40:in `call'
 /app/objects/trackedjob.rb:33:in call'
 /app/objects/safe_job.rb:36:in call'
 /app/objects/asyncjob.rb:44:in `block (2 levels) in call'
 /app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
 /app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `opensynchronized'
 /app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in open'
 /app/objects/async_job.rb:43:in block in call'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:348:in `runtask'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:337:in `block (3 levels) in createworker'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:320:in `loop'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:320:in block (2 levels) in create_worker'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in catch'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:319:in `block in createworker'"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)the tuition fee $0.93 was deducted and sent to @denis-konovalyenko/z (https://www.0crat.com/u/denis-konovalyenko) (your mentor), according to §45 (http://www.zerocracy.com/policy.html#45)
```
See https://github.com/zerocracy/farm/issues/2098

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it's a regular situation. You just have to try again in a few minutes and that's all. This error means that no master nodes are visible at the moment.

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#271` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
