### ISSUE TITLE
can't parse time

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#287]
```
Zold::Txn::CantParseTime: Invalid ISO 8601 date "2019-06-13"
  from zold/txn.rb:200:in `parse_time'
  from front/front_callbacks.rb:149:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/csrf.rb:38:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from rack/ssl.rb:27:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from thin/connection.rb:86:in `block in pre_process'
  from thin/connection.rb:84:in `catch'
  from thin/connection.rb:84:in `pre_process'
  from thin/connection.rb:53:in `process'
  from thin/connection.rb:39:in `receive_data'
  from eventmachine.rb:195:in `run_machine'
  from eventmachine.rb:195:in `run'
  from thin/backends/base.rb:73:in `start'
  from thin/server.rb:162:in `start'
  from rack/handler/thin.rb:22:in `run'
  from rack/server.rb:297:in `start'
  from rack/server.rb:148:in `start'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/bin/rackup:4:in `<top (required)>'
  from vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
  from vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:463:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  from bundler/cli.rb:27:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from bundler/cli.rb:18:in `start'
  from vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:124:in `with_friendly_errors'
  from vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
  from vendor/bundle/bin/bundle:104:in `load'
  from vendor/bundle/bin/bundle:104:in `<main>'

```

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#287` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
