### ISSUE TITLE
Server error when logging in via GitHub

### ISSUE THREAD

**Issue by byzantime** [zold-io/wts.zold.io#3]
Received this response when already logged into GitHub, clicking on the "Authorize zold-io" button:
```
 Internal error at 0.0.1

Please help us improve our service and submit the following stacktrace to our issue tracker in GitHub: zold-io/wts.zold.io

Failed to open TCP connection to github.com:443 (undefined method `[]' for nil:NilClass)
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	/app/vendor/bundle/ruby/2.3.0/gems/glogin-0.2.2/lib/glogin/auth.rb:83:in `access_token'
	/app/vendor/bundle/ruby/2.3.0/gems/glogin-0.2.2/lib/glogin/auth.rb:62:in `user'
	/app/wts.rb:86:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.2/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.2/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.2/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.2/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.2/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.2/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1958:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.2/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@byzantime[/z](https://www.0crat.com/u/byzantime) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#3](https://github.com/zold-io/wts.zold.io/issues/3) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @byzantime[/z](https://www.0crat.com/u/byzantime)! If you would be a member of [the project](https://www.0crat.com/p/CB28FH2NR), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#3](https://github.com/zold-io/wts.zold.io/issues/3); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@byzantime seems to be fixed. If not, report a new ticket.

**Comment by 0crat** [comment]
The job [#3](https://github.com/zold-io/wts.zold.io/issues/3) is now out of scope
