### ISSUE TITLE
Haml::Error: Invalid US-ASCII character "\xE2"

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#301]
```
Haml::Error: Invalid US-ASCII character "\xE2"
  from haml/engine.rb:57:in `block in initialize'
  from haml/util.rb:81:in `rescue in block in check_encoding'
  from haml/util.rb:78:in `block in check_encoding'
  from haml/util.rb:77:in `each'
  from haml/util.rb:77:in `each_with_index'
  from haml/util.rb:77:in `check_encoding'
  from haml/util.rb:117:in `check_haml_encoding'
  from haml/engine.rb:56:in `initialize'
  from front/front_quick.rb:30:in `new'
  from front/front_quick.rb:30:in `block in <top (required)>'
```

See in #235 already

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.51`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.51`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.51`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#301` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
