### ISSUE TITLE
Pulling error

### ISSUE THREAD

**Issue by vladarefiev** [zold-io/wts.zold.io#303]
Trying to pull wallet to check balance, but log has some errors:

```
Zold gem version: 0.29.30/2
WTS version: 0.35.51
Current time is: 2019-10-14T13:28:41Z
Job ID: dd1fcece-8435-4ed5-aa7d-508d47a30a74
Login: 79066700808
Pulling wallet 718a5f671beeb877 via /pull...
Removing the local copy of 718a5f671beeb877...
Wallet 718a5f671beeb877 file not found in /app/.zold-wts/wallets/718a5f671beeb877.z
Wallet 718a5f671beeb877 removed
Pulling 718a5f671beeb877 from the network...
ERROR: WTS::UserError: E186: We didn't manage to find your wallet 718a5f671beeb877 in any of visible Zold nodes (79066700808). You should try to PULL again. If it doesn't work, most likely your wallet 718a5f671beeb877 is lost and can't be recovered. If you have its copy locally, you can push it to the network from the console app, using PUSH command. Otherwise, go for the RESTART option in the top menu and create a new wallet. We are sorry to see this happening! No nodes out of 20 have the wallet 718a5f671beeb877; run 'zold remote update' and try again
	/app/objects/ops.rb:90:in `rescue in pull'
	/app/objects/ops.rb:84:in `pull'
	/app/front/front_start.rb:94:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vladarefiev[/z](https://www.0crat.com/u/vladarefiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@vladarefiev this means that your wallet is gone from the network, you should create a new one. Click "Restart"

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#303` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
