### ISSUE TITLE
ZLD -> PayPal Failed: User is not allowed to perform this action

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/wts.zold.io#320]
I've tried exchanging 10 ZLD to PayPal (I am a member of Zerocracy, so I should be able to) and got the following exception in the Log (**"User is not allowed to perform this action"**): 

```
ERROR: RuntimeError: Failed to send $25.49 to "amihaiemil@gmail.com" with details of "Zerocracy development, TID 38dfc77fede6b721:1": {"responseEnvelope":{"timestamp":"2020-01-28T04:11:31.945-08:00","ack":"Failure","correlationId":"3200fc4ed49d2","build":"apapiserv-0.0.1_20200106071415014"},"error":[{"errorId":"550001","domain":"PLATFORM","subdomain":"Application","severity":"Error","category":"Application","message":"User is not allowed to perform this action"}]}
	/app/objects/paypal.rb:62:in `pay'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:45:in `block in method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `method_missing'
	/app/front/front_paypal.rb:123:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/exclusive_job.rb:35:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/exclusive_job.rb:34:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

I received nothing on PayPal, but the sum was deducted from my wallet: 

![image](https://user-images.githubusercontent.com/6305156/73263537-72ec0300-41d9-11ea-8b01-ccd077e5593b.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@yegor256 Can you please have a look? 

Could this Issue be because of the fact that I have reputation < 256? However, I am a long term member of ZC and I don't even have a mentor anymore (at some point I had over 2048 rep).

**Comment by yegor256** [comment]
@amihaiemil this was a bug on our side. We will send you PayPal now.

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#320` is not assigned, can't get performer
