### ISSUE TITLE
Payment was lost - attempted to withdraw to Paypal

### ISSUE THREAD

**Issue by carlosmiranda** [zold-io/wts.zold.io#330]
I tried to withdraw funds today to my paypal. My wallet got deducted, but the payment failed with the following error:

```
ERROR: RuntimeError: Failed to send $xxx.xxx to "...@gmail.com" with details of "Zerocracy development, TID 43c46fa1d2a5bfb5:22": {"responseEnvelope":{"timestamp":"2020-02-16T17:38:42.127-08:00","ack":"Failure","correlationId":"487cb692a5675","build":"apapiserv-0.0.1_20200106071415014"},"error":[{"errorId":"589009","domain":"PLATFORM","subdomain":"Application","severity":"Error","category":"Application","message":"The payment can not be processed because no payment source is available","parameter":["GetSplitFundingPlan did not return a funding plan"]}]}
	/app/objects/paypal.rb:62:in `pay'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:45:in `block in method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `method_missing'
	/app/front/front_paypal.rb:123:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/exclusive_job.rb:35:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/exclusive_job.rb:34:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by carlosmiranda** [comment]
@yegor256 sent you the full log via Telegram

**Comment by yegor256** [comment]
@carlosmiranda resolved

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#330` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
