### ISSUE TITLE
undefined method `valid_encoding?'

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#332]
```
NoMethodError: undefined method `valid_encoding?' for ["php"]:Array
  from front/front_login.rb:92:in `block (2 levels) in <top (required)>'
  from front/front_login.rb:90:in `each'
  from front/front_login.rb:90:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
```

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#332` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
