### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#333]
```
NoMethodError: undefined method `[]' for nil:NilClass
  from objects/assets.rb:223:in `monitor_btc'
  from syncem.rb:45:in `block in method_missing'
  from syncem.rb:43:in `synchronize'
  from syncem.rb:43:in `method_missing'
  from front/front_btc.rb:97:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.6`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#333` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
