### ISSUE TITLE
Your wallet doesn't exist on our server yet

### ISSUE THREAD

**Issue by fevzian** [zold-io/wts.zold.io#336]
I have been experiencing an issue with zold wallet. 
@0crat informs that the payments cannot be done, as the wallet is not found. 
The https://wts.zold.io/ shows a message: `Your wallet doesn't exist on our server yet.`

I also pulled the logs for my wallet:
```
The list of 18 remotes trimmed down to 18 nodes (5 masters)
104.248.82.243:4096/0: "The node 127.0.0.1:4096 is not responding, 599:" in 331ms
213.219.36.162:4096/4: "The node 127.0.0.1:4096 is not responding, 599:" in 141ms
5.9.141.146:4096/2: "The node 127.0.0.1:4096 is not responding, 599:" in 972ms
128.199.160.210:4096/3: "The node 127.0.0.1:4096 is not responding, 599:" in 1.27s
zold1.mooo.com:80/7: "The node 127.0.0.1:4096 is not responding, 599:" in 97ms
z0.kkona.xyz:4096/1: "The node 127.0.0.1:4096 is not responding, 599:" in 1.41s
46.101.177.53:4096/8: "The node 127.0.0.1:4096 is not responding, 599:" in 344ms
172.105.3.25:4096/5: "The node 127.0.0.1:4096 is not responding, 599:" in 1.29s
128.199.161.35:4096/9: "The node 127.0.0.1:4096 is not responding, 599:" in 590ms
z4.kkona.xyz:4096/12: "The node 127.0.0.1:4096 is not responding, 599:" in 589ms
b2.zold.io:4096/13: "The node 127.0.0.1:4096 is not responding, 599:" in 453ms
128.199.161.13:4096/10: "The node 127.0.0.1:4096 is not responding, 599:" in 1.17s
138.197.140.42:4096/16: "The node 127.0.0.1:4096 is not responding, 599:" in 488ms
167.99.77.100:4096/17: "The node 127.0.0.1:4096 is not responding, 599:" in 992ms
kkona.xyz:4096/22: "The node 127.0.0.1:4096 is not responding, 599:" in 145ms
zold2.mooo.com:80/18: "The node 127.0.0.1:4096 is not responding, 599:" in 285ms
188.166.17.39:4096/21: "The node 127.0.0.1:4096 is not responding, 599:" in 356ms
157.230.21.175:4096/24: "The node 127.0.0.1:4096 is not responding, 599:" in 88ms
144.91.117.3:4096/23: "The node 127.0.0.1:4096 is not responding, 599:" in 335ms
157.230.103.89:4096/27: "The node 127.0.0.1:4096 is not responding, 599:" in 282ms
There are 40 known remotes (5 masters) with the overall score of 2143, after update in 6.11s
21 best remote nodes were selected to stay in the list (5 masters)
---
Zold gem version: 0.29.33/2
WTS version: 0.36.8
Current time is: 2020-02-28T15:41:51Z
Job ID: d1221a0d-ee0a-4e59-9b11-59b11e7997b7
Login: fanifieiev
Pulling wallet 215c0341d7c40599 via /pull...
Removing the local copy of 215c0341d7c40599...
Wallet 215c0341d7c40599 file not found in /app/.zold-wts/wallets/215c0341d7c40599.z
Wallet 215c0341d7c40599 removed
Pulling 215c0341d7c40599 from the network...
ERROR: WTS::UserError: E186: We didn't manage to find your wallet 215c0341d7c40599 in any of visible Zold nodes (fanifieiev). You should try to PULL again. If it doesn't work, most likely your wallet 215c0341d7c40599 is lost and can't be recovered. If you have its copy locally, you can push it to the network from the console app, using PUSH command. Otherwise, go for the RESTART option in the top menu and create a new wallet. We are sorry to see this happening! No nodes out of 21, incl. 0 master, have the wallet 215c0341d7c40599; run 'zold remote update' and try again
	/app/objects/ops.rb:90:in `rescue in pull'
	/app/objects/ops.rb:84:in `pull'
	/app/front/front_start.rb:94:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
The list of 40 remotes trimmed down to 40 nodes (5 masters)
z0.kkona.xyz:4096/1: "The node 127.0.0.1:4096 is not responding, 599:" in 290ms
5.9.141.146:4096/2: "The node 127.0.0.1:4096 is not responding, 599:" in 367ms
104.248.82.243:4096/0: "The node 127.0.0.1:4096 is not responding, 599:" in 489ms
128.199.160.210:4096/3: "The node 127.0.0.1:4096 is not responding, 599:" in 734ms
213.219.36.162:4096/4: "The node 127.0.0.1:4096 is not responding, 599:" in 901ms
46.101.177.53:4096/7: "The node 127.0.0.1:4096 is not responding, 599:" in 848ms
zold1.mooo.com:80/6: "The node 127.0.0.1:4096 is not responding, 599:" in 1.19s
b2.zold.io:4096/11: "The node 127.0.0.1:4096 is not responding, 599:" in 246ms
z4.kkona.xyz:4096/10: "The node 127.0.0.1:4096 is not responding, 599:" in 562ms
128.199.161.35:4096/8: "The node 127.0.0.1:4096 is not responding, 599:" in 1.24s
128.199.161.13:4096/9: "The node 127.0.0.1:4096 is not responding, 599:" in 1.29s
159.203.19.189:4096/13: "The node 127.0.0.1:4096 is not responding, 599:" in 672ms
157.230.103.89:4096/17: "The node 127.0.0.1:4096 is not responding, 599:" in 353ms
kkona.xyz:4096/23: "The node 127.0.0.1:4096 is not responding, 599:" in 327ms
167.99.77.100:4096/15: "The node 127.0.0.1:4096 is not responding, 599:" in 1.44s
157.230.21.175:4096/26: "The node 127.0.0.1:4096 is not responding, 599:" in 350ms
18.217.109.153:4096/25: "The node 127.0.0.1:4096 is not responding, 599:" in 576ms
188.166.17.39:4096/30: "The node 127.0.0.1:4096 is not responding, 599:" in 393ms
zold2.mooo.com:80/33: "The node 127.0.0.1:4096 is not responding, 599:" in 763ms
There are 40 known remotes (5 masters) with the overall score of 2130, after update in 6.65s
16 best remote nodes were selected to stay in the list (5 masters)
---
Zold gem version: 0.29.33/2
WTS version: 0.36.8
Current time is: 2020-02-28T15:42:45Z
Job ID: 3e3c42f1-0c8f-48ed-a55f-fe6626051e3b
Login: fanifieiev
Pulling wallet 215c0341d7c40599 via /pull...
Removing the local copy of 215c0341d7c40599...
Wallet 215c0341d7c40599 file not found in /app/.zold-wts/wallets/215c0341d7c40599.z
Wallet 215c0341d7c40599 removed
Pulling 215c0341d7c40599 from the network...
ERROR: WTS::UserError: E186: We didn't manage to find your wallet 215c0341d7c40599 in any of visible Zold nodes (fanifieiev). You should try to PULL again. If it doesn't work, most likely your wallet 215c0341d7c40599 is lost and can't be recovered. If you have its copy locally, you can push it to the network from the console app, using PUSH command. Otherwise, go for the RESTART option in the top menu and create a new wallet. We are sorry to see this happening! No nodes out of 16, incl. 0 master, have the wallet 215c0341d7c40599; run 'zold remote update' and try again
	/app/objects/ops.rb:90:in `rescue in pull'
	/app/objects/ops.rb:84:in `pull'
	/app/front/front_start.rb:94:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
The list of 18 remotes trimmed down to 18 nodes (5 masters)
5.9.141.146:4096/3: "The node 127.0.0.1:4096 is not responding, 599:" in 1.15s
172.105.3.25:4096/0: "The node 127.0.0.1:4096 is not responding, 599:" in 1.49s
18.217.229.130:4096/8: "The node 127.0.0.1:4096 is not responding, 599:" in 448ms
159.203.63.90:4096/14: "The node 127.0.0.1:4096 is not responding, 599:" in 492ms
b2.zold.io:4096/13: "The node 127.0.0.1:4096 is not responding, 599:" in 769ms
159.203.19.189:4096/15: "The node 127.0.0.1:4096 is not responding, 599:" in 565ms
167.99.77.100:4096/17: "The node 127.0.0.1:4096 is not responding, 599:" in 635ms
138.197.140.42:4096/16: "The node 127.0.0.1:4096 is not responding, 599:" in 1.28s
zold1.mooo.com:80/17: "The node 127.0.0.1:4096 is not responding, 599:" in 109ms
193.37.152.101:4096/22: "The node 127.0.0.1:4096 is not responding, 599:" in 590ms
188.166.17.39:4096/23: "The node 127.0.0.1:4096 is not responding, 599:" in 666ms
3.18.62.3:4096/24: "The node 127.0.0.1:4096 is not responding, 599:" in 760ms
167.86.77.182:4096/25: "The node 127.0.0.1:4096 is not responding, 599:" in 844ms
134.209.86.97:4096/31: "The node 127.0.0.1:4096 is not responding, 599:" in 145ms
z2.kkona.xyz:4096/28: "The node 127.0.0.1:4096 is not responding, 599:" in 606ms
128.199.161.13:4096/30: "The node 127.0.0.1:4096 is not responding, 599:" in 1.04s
There are 40 known remotes (5 masters) with the overall score of 2131, after update in 9.02s
17 best remote nodes were selected to stay in the list (5 masters)
---
Zold gem version: 0.29.33/2
WTS version: 0.36.8
Current time is: 2020-02-28T16:59:05Z
Job ID: 92dc1341-c870-4cbe-a7aa-617a560bc62d
Login: fanifieiev
Pulling wallet 215c0341d7c40599 via /pull...
Removing the local copy of 215c0341d7c40599...
Wallet 215c0341d7c40599 file not found in /app/.zold-wts/wallets/215c0341d7c40599.z
Wallet 215c0341d7c40599 removed
Pulling 215c0341d7c40599 from the network...
ERROR: WTS::UserError: E186: We didn't manage to find your wallet 215c0341d7c40599 in any of visible Zold nodes (fanifieiev). You should try to PULL again. If it doesn't work, most likely your wallet 215c0341d7c40599 is lost and can't be recovered. If you have its copy locally, you can push it to the network from the console app, using PUSH command. Otherwise, go for the RESTART option in the top menu and create a new wallet. We are sorry to see this happening! No nodes out of 19, incl. 0 master, have the wallet 215c0341d7c40599; run 'zold remote update' and try again
	/app/objects/ops.rb:90:in `rescue in pull'
	/app/objects/ops.rb:84:in `pull'
	/app/front/front_start.rb:94:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'


If you see any errors here, which you don't understand, please submit an issue to our GitHub repository here and copy the entire log over there: https://github.com/zold-io/wts.zold.io/issues; we need your feedback in order to make our system better; you can also discuss it in our Telegram group: https://t.me/zold_io.
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
