### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#350]
```
Sibit::Error: Amount should either be a String or Integer, Float provided
  from sibit.rb:277:in `satoshi'
  from sibit.rb:123:in `pay'
  from objects/assets.rb:184:in `pay'
  from syncem.rb:45:in `block in method_missing'
  from syncem.rb:43:in `synchronize'
  from syncem.rb:43:in `method_missing'
  from front/front_btc.rb:203:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
ADDITIONAL DATA
```

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#350` is not assigned, can't get performer
