### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#351]
```
NoMethodError: undefined method `[]' for nil:NilClass
  from sibit/btc.rb:72:in `next_of'
  from retriable_proxy.rb:34:in `public_send'
  from retriable_proxy.rb:34:in `block in method_missing'
  from retriable_proxy.rb:43:in `block in __retrying'
  from retriable.rb:61:in `block in retriable'
  from retriable.rb:57:in `times'
  from retriable.rb:57:in `retriable'
  from retriable_proxy.rb:43:in `__retrying'
  from retriable_proxy.rb:34:in `method_missing'
  from sibit.rb:94:in `block in next_of'
  from sibit.rb:251:in `block in first_one'
  from sibit.rb:249:in `each'
  from sibit.rb:249:in `first_one'
  from sibit.rb:93:in `next_of'
  from objects/assets.rb:156:in `monitor'
  from syncem.rb:45:in `block in method_missing'
  from syncem.rb:43:in `synchronize'
  from syncem.rb:43:in `method_missing'
  from front/front_btc.rb:102:in `block in <top (required)>'
  from objects/daemons.rb:44:in `block (2 levels) in start'
  from objects/daemons.rb:40:in `loop'
  from objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.1`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#351` is not assigned, can't get performer
