### ISSUE TITLE
Unexpected error while processing request: undefined local variable or method `ver'

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#370]
```
Unexpected error while processing request: undefined local variable or method `ver' for #<Sinatra::Application:0x000055b4f09a70e0>
2020-08-24T18:37:49.560045956Z app[web.1]: 	/app/views/error.haml:6:in `__tilt_47117808709980'
2020-08-24T18:37:49.560050713Z app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
2020-08-24T18:37:49.560054849Z app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
2020-08-24T18:37:49.560058841Z app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/haml.rb:24:in `evaluate'
2020-08-24T18:37:49.560062852Z app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
2020-08-24T18:37:49.560066866Z app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:839:in `render'
2020-08-24T18:37:49.560070827Z app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:692:in `haml'
2020-08-24T18:37:49.560074752Z app[web.1]: 	/app/front/front_errors.rb:46:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.15`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#370` is not assigned, can't get performer
