### ISSUE TITLE
NameError: undefined local variable or method `fee' for #<Sinatra::Application:0x00007f305800a5e8>

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#371]
```
NameError: undefined local variable or method `fee' for #<Sinatra::Application:0x00007f305800a5e8>
	/app/views/rate.haml:68:in `__tilt_46933642989740'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/haml.rb:24:in `evaluate'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:839:in `render'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:692:in `haml'
	/app/front/front_rate.rb:105:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.16`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#371` is not assigned, can't get performer
