### ISSUE TITLE
undefined method `start_with?' in assets.rb

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#377]
```
NoMethodError: undefined method `start_with?' for []:Array
2020-09-20T15:29:19.632003196Z app[web.1]:    	/app/objects/assets.rb:156:in `monitor'
2020-09-20T15:29:19.632022577Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:45:in `block in method_missing'
2020-09-20T15:29:19.632029003Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `synchronize'
2020-09-20T15:29:19.632034493Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `method_missing'
2020-09-20T15:29:19.632039920Z app[web.1]:    	/app/front/front_btc.rb:104:in `block in <top (required)>'
2020-09-20T15:29:19.632045443Z app[web.1]:    	/app/objects/daemons.rb:44:in `block (2 levels) in start'
2020-09-20T15:29:19.632050726Z app[web.1]:    	/app/objects/daemons.rb:40:in `loop'
2020-09-20T15:29:19.632055889Z app[web.1]:    	/app/objects/daemons.rb:40:in `block in start'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.21`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#377` is not assigned, can't get performer
