### ISSUE TITLE
lost wallet breaks blockchain screening

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#397]
```
2021-03-07T12:16:49.693516302Z app[web.1]: E: Zold::Fetch::NotFound: No nodes out of 16, incl. 0 master, have the wallet xxxx; run 'zold remote update' and try again
2021-03-07T12:16:49.693574960Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/fetch.rb:129:in `fetch'
2021-03-07T12:16:49.693594285Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/fetch.rb:105:in `block in run'
2021-03-07T12:16:49.693606993Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/hands.rb:75:in `block in exec'
2021-03-07T12:16:49.693616762Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/hands.rb:75:in `each'
2021-03-07T12:16:49.693625641Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/hands.rb:75:in `each_with_index'
2021-03-07T12:16:49.693634425Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/hands.rb:75:in `exec'
2021-03-07T12:16:49.693643232Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/fetch.rb:104:in `run'
2021-03-07T12:16:49.693651913Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/thread_badge.rb:41:in `run'
2021-03-07T12:16:49.693660668Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/pull.rb:47:in `run'
2021-03-07T12:16:49.693669444Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/thread_badge.rb:41:in `run'
2021-03-07T12:16:49.693678286Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/invoice.rb:76:in `invoice'
2021-03-07T12:16:49.693687127Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/invoice.rb:68:in `run'
2021-03-07T12:16:49.693695714Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/thread_badge.rb:41:in `run'
2021-03-07T12:16:49.693704501Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/pay.rb:96:in `run'
2021-03-07T12:16:49.693713206Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/thread_badge.rb:41:in `run'
2021-03-07T12:16:49.693721847Z app[web.1]:    	/app/objects/ops.rb:171:in `block in pay'
2021-03-07T12:16:49.693730387Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tempfile.rb:295:in `open'
2021-03-07T12:16:49.693738831Z app[web.1]:    	/app/objects/ops.rb:168:in `pay'
2021-03-07T12:16:49.693747012Z app[web.1]:    	/app/front/front_btc.rb:114:in `block (2 levels) in <top (required)>'
2021-03-07T12:16:49.693755802Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:46:in `block (2 levels) in method_missing'
2021-03-07T12:16:49.693771604Z app[web.1]:    	/app/objects/assets.rb:174:in `block in monitor'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.37`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.38`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.38`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#397` is not assigned, can't get performer
