### ISSUE TITLE
failure on paying hosting bonuses

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#403]
```
ERROR: RuntimeError: There is not enough funds in 9b34e43da59e0fe2 to send 0.12ZLD, only 0.02ZLD left; the difference is 451081823 zents
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/pay.rb:141:in `pay'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/pay.rb:107:in `block in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/sync_wallets.rb:47:in `block (2 levels) in acq'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/sync_wallets.rb:46:in `block in acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/cached_wallets.rb:51:in `block in acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/wallets.rb:71:in `acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/cached_wallets.rb:49:in `acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/sync_wallets.rb:45:in `acq'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/pay.rb:106:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.33/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/objects/ops.rb:171:in `block in pay'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:168:in `pay'
	/app/front/front_bonuses.rb:58:in `block in pay_hosting_bonuses'
	/app/front/front_bonuses.rb:56:in `each'
	/app/front/front_bonuses.rb:56:in `pay_hosting_bonuses'
	/app/front/front_bonuses.rb:26:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:48:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.41`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.41`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.41`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.41`

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.41`
