### ISSUE TITLE
RuntimeError: Keygap can't be nil

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#49]
```
ERROR: RuntimeError: Keygap can't be nil
/app/objects/ops.rb:70:in `pay'
	/app/objects/update_ops.rb:53:in `pay'
	/app/objects/latch_ops.rb:48:in `pay'
	/app/objects/versioned_ops.rb:46:in `pay'
	/app/objects/safe_ops.rb:45:in `pay'
	/app/objects/async_ops.rb:46:in `block in pay'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#49` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
