### ISSUE TITLE
WTS signup bonus has not been awarded

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/wts.zold.io#68]
Wallet ID: e560c4fb95684c6d. It has not been awarded by 8.00 ZLD signup bonus up to now for some reasons, however it was created on the 31th of August, 2018:

```
Wallet e560c4fb95684c6d created at /app/.zold-wts/wallets
e560c4fb95684c6d
Wallet e560c4fb95684c6d created successfully
Wallet e560c4fb95684c6d created and pushed by @denis-konovalyenko
Zold gem version: 0.14.38/2
45.77.55.65:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 1.31s: 21 (0.14.38)
159.203.63.90:4096: Expired score 3/6: 2018-08-19T06:32:43Z 159.203.63.90 4096 lO271Qsy@912ecc24b32dbe74 10e9c0d 3a4cf9 610f23 in 1s
RuntimeError: Expired score 3/6: 2018-08-19T06:32:43Z 159.203.63.90 4096 lO271Qsy@912ecc24b32dbe74 10e9c0d 3a4cf9 610f23
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:92:in `assert_valid_score'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:104:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
138.201.231.23:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 1.59s: 22 (0.14.38)
b1.zold.io:80/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 1.84s: 0 (0.14.38)
159.203.19.189:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 2.18s: 9 (0.14.38)
z.oltdaniel.tk:4096: Bad Request (HTTP code 400, instead of 200) in 2s
RuntimeError: Bad Request (HTTP code 400, instead of 200)
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:87:in `assert_code'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:101:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
37.230.116.39:4096: Bad Request (HTTP code 400, instead of 200) in 2s
RuntimeError: Bad Request (HTTP code 400, instead of 200)
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:87:in `assert_code'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:101:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
167.99.77.100:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 2.76s: 22 (0.14.38)
138.197.140.42:4096: Expired score 2/6: 2018-08-22T20:39:09Z 138.197.140.42 4096 rF8hBM7j@912ecc24b32dbe74 4f083b 65a3a6 in 3s
RuntimeError: Expired score 2/6: 2018-08-22T20:39:09Z 138.197.140.42 4096 rF8hBM7j@912ecc24b32dbe74 4f083b 65a3a6
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:92:in `assert_valid_score'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:104:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
138.68.95.144:4096: Expired score 11/6: 2018-08-23T14:20:13Z 138.68.95.144 4096 paDRj2g1@62e329426a673e68 c23f1e 288ec1d d59487 216248 a49a50 10a23a1 8e659a 3bcfa2 169cfb 2d66b7 31bb97 in 3s
RuntimeError: Expired score 11/6: 2018-08-23T14:20:13Z 138.68.95.144 4096 paDRj2g1@62e329426a673e68 c23f1e 288ec1d d59487 216248 a49a50 10a23a1 8e659a 3bcfa2 169cfb 2d66b7 31bb97
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:92:in `assert_valid_score'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:104:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
162.244.34.31:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 3.2s: 32 (0.14.38)
62.113.238.236:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 7.38s: 17 (0.14.38)
62.113.238.234:4096/0 accepted 418b/5db245/0t of e560c4fb95684c6d in 9.62s: 16 (0.14.38)
b2.zold.io:4096: Expired score 9/6: 2018-08-19T12:20:17Z b2.zold.io 4096 kiG9w0BA@912ecc24b32dbe74 adcbd9 ed5c77 bf0f6 869ae5 437b6a 17e0300 1768685 237cd1 115919f in 28s
RuntimeError: Expired score 9/6: 2018-08-19T12:20:17Z b2.zold.io 4096 kiG9w0BA@912ecc24b32dbe74 adcbd9 ed5c77 bf0f6 869ae5 437b6a 17e0300 1768685 237cd1 115919f
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:92:in `assert_valid_score'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:104:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
46.38.239.39:4096: Net::ReadTimeout (HTTP code 599, instead of 200) in 32s
RuntimeError: Net::ReadTimeout (HTTP code 599, instead of 200)
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:87:in `assert_code'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:101:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
18.222.138.218:4096: Net::ReadTimeout (HTTP code 599, instead of 200) in 34s
RuntimeError: Net::ReadTimeout (HTTP code 599, instead of 200)
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:87:in `assert_code'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:101:in `block in push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `open'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:55:in `block in find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/wallets.rb:66:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/sync_wallets.rb:52:in `find'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:95:in `push_one'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/commands/push.rb:75:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.38/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
Push finished to 8 nodes out of 16 in 34s, total score for e560c4fb95684c6d is 16
ERROR: NameError: undefined local variable or method `id' for #<Ops:0x007f958c66e9e0>
/app/objects/ops.rb:65:in `push'
	/app/objects/update_ops.rb:47:in `push'
	/app/objects/latch_ops.rb:41:in `push'
	/app/objects/versioned_ops.rb:41:in `push'
	/app/objects/safe_ops.rb:39:in `push'
	/app/objects/async_ops.rb:40:in `block in push'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Account confirmed for @denis-konovalyenko
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@denis-konovalyenko This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#68` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by denis-konovalyenko** [comment]
@yegor256 , thanks for the clarification!

May I hope for crediting my wallet (e560c4fb95684c6d) with 8 ZLD at some point in time then (whether it is possible to issue this transaction manually)?
