### ISSUE TITLE
broken JSON

### ISSUE THREAD

**Issue by yegor256** [zold-io/wts.zold.io#75]
```
RuntimeError: JSON is empty, can't parse
  from zold/json_page.rb:40:in `to_hash'
  from objects/btc.rb:51:in `exists?'
  from wts.rb:382:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:990:in `block in route!'
  from sinatra/base.rb:989:in `each'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:1097:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/ssl.rb:27:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from thin/connection.rb:86:in `block in pre_process'
  from thin/connection.rb:84:in `catch'
  from thin/connection.rb:84:in `pre_process'
  from thin/connection.rb:53:in `process'
  from thin/connection.rb:39:in `receive_data'
  from eventmachine.rb:195:in `run_machine'
  from eventmachine.rb:195:in `run'
  from thin/backends/base.rb:73:in `start'
  from thin/server.rb:162:in `start'
  from rack/handler/thin.rb:22:in `run'
  from rack/server.rb:297:in `start'
  from rack/server.rb:148:in `start'
  from vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
  from vendor/bundle/ruby/2.5.0/bin/rackup:23:in `load'
  from vendor/bundle/ruby/2.5.0/bin/rackup:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:27:in `run'
  from bundler/cli.rb:360:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
  from bundler/cli.rb:20:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:444:in `start'
  from bundler/cli.rb:10:in `start'
  from vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:121:in `with_friendly_errors'
  from vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
  from vendor/bundle/ruby/2.5.0/bin/bundle:22:in `load'
  from vendor/bundle/ruby/2.5.0/bin/bundle:22:in `<main>'
```

**Comment by 0crat** [comment]
The job [#75](https://github.com/zold-io/wts.zold.io/issues/75) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/84f2ce70-88b7-477b-ac93-4f939bf3b23a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#75` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`
