### ISSUE TITLE
Bitcoin address not accepted during ZLD to BTC operation

### ISSUE THREAD

**Issue by victornoel** [zold-io/wts.zold.io#81]
I tried to transform some zold into btc and entered a normal BTC address (a plain string with random characters and numbers, starting with bc1q, generated with the electrum btc client), the WTS failed and said:
```
Coinbase::Wallet::ValidationError: Please enter a valid email or Bitcoin address
	/app/vendor/bundle/ruby/2.5.0/gems/coinbase-4.1.0/lib/coinbase/wallet/api_errors.rb:45:in `check_response_status'
	/app/vendor/bundle/ruby/2.5.0/gems/coinbase-4.1.0/lib/coinbase/wallet/adapters/net_http.rb:36:in `http_verb'
	/app/vendor/bundle/ruby/2.5.0/gems/coinbase-4.1.0/lib/coinbase/wallet/api_client.rb:685:in `post'
	/app/vendor/bundle/ruby/2.5.0/gems/coinbase-4.1.0/lib/coinbase/wallet/api_client.rb:268:in `send'
	/app/vendor/bundle/ruby/2.5.0/gems/coinbase-4.1.0/lib/coinbase/wallet/models/account.rb:61:in `send'
	/app/objects/bank.rb:46:in `send'
	/app/wts.rb:452:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/app/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/app/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/app/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/handler/thin.rb:22:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
	/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
	/app/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `load'
	/app/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `<top (required)>'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
	/app/vendor/bundle/ruby/2.5.0/bin/bundle:22:in `load'
	/app/vendor/bundle/ruby/2.5.0/bin/bundle:22:in `<main>'
```

I suppose it is expecting some kind of special format for the address but this is explained nowhere...

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#81](https://github.com/zold-io/wts.zold.io/issues/81) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB28FH2NR/73f28c09-b517-4a1f-b206-c983bc68b7a2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#81` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by yegor256** [comment]
@victornoel This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job [#81](https://github.com/zold-io/wts.zold.io/issues/81) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
