### ISSUE TITLE
"No nodes have a wallet" error when attempting to pull it

### ISSUE THREAD

**Issue by filfreire** [zold-io/wts.zold.io#92]
@yegor256 I opened the logs after `Pulling my wallet` (wallet is `106f5919118568f1`) and got the following error message:

```
ERROR: RuntimeError: No nodes out of 14 have the wallet 106f5919118568f1; run 'zold remote update' and try again
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/commands/fetch.rb:116:in `fetch'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/commands/fetch.rb:95:in `block in run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/thread_pool.rb:47:in `block in run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/thread_pool.rb:47:in `each'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/thread_pool.rb:47:in `each_with_index'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/thread_pool.rb:47:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/commands/fetch.rb:94:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/commands/pull.rb:47:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.21.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/objects/ops.rb:45:in `pull'
	/app/wts.rb:327:in `block (2 levels) in <top (required)>'
	/app/wts.rb:647:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/clean_job.rb:39:in `call'
	/app/objects/versioned_job.rb:34:in `call'
	/app/objects/safe_job.rb:34:in `call'
	/app/objects/async_job.rb:46:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:124:in `block in open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/objects/async_job.rb:45:in `block in call'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'



If you see any errors here, which you don't understand, please submit an issue to our GitHub repository here and copy the entire log over there: https://github.com/zold-io/wts.zold.io/issues; we need your feedback in order to make our system better; you can also discuss it in our Telegram group: https://t.me/zold_io.

```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.3`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#92` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
